#Madlib Game
#input() - take input from the user

number1 = input("Please enter a number")
#print(number1)
noun1 = input("Please enter a noun")
#print(noun1)
verb1 = input("Please enter a verb")
#print(verb1)
adj1 = input("Please enter an adjective")
#print(adj1)
number2 = input("Please enter a number")
#print(number2)
place1 = input("Please enter a place")
#print(place1)
firstName1 = input("Please enter a name")
#print(firstName1)
firstName2 = input"Please enter a name")
#print(firstName2)
verbEd1 = input("Please enter a verb")
#print(verbEd1)
noun2 = input("Please enter a noun")
#print(noun2)
adj2 = input("Please enter an adjective")
#print(adj2)
adj3 = input("Please enter an adjective")
#print(adj3)
verbEd2 = input("Please enter a verb-ed")
#print(verbEd2)
verbEd3 = input("Please enter a verb-ed")
#print(verbEd3)
noun3 = input("Please enter a noun")
#print(noun3)
verbEd4 = input("Please enter a verb-ed")
#print(verbEd4)
pluralNoun1 = input("Please enter a plural noun")
#print(pluralNoun1)
verb2 = input("Please enter a verb")
#print(verb2)
adverb1 = input("Please enter an adverb")
#print(adverb1)
number3 = input("Please enter a number")
#print(number3)


madlib = "firstpart " + number1 + " second part" + noun1 + "third part" + verb1 + "fourth part" + adj1 + "fifth part" + number2 + "sixth part" + place1 + "seventh part" + firstName1 + "eigth part" + firstName2 + "ninth part" + verbEd1 + "tenth part" + noun2 + "eleventh part" + adj2 = "twelveth part" + adj3 + "thirteenth part" + 
