import turtle
leo = turtle.Turtle()
leo.color("brown")
leo.shape("turtle")
leo.begin_fill()
leo.penup()
leo.right(90)
leo.forward(370)
leo.right(90)
leo.forward(100)
leo.pendown()
leo.right(90)
leo.forward(100)
leo.right(90)
leo.forward(100)
leo.right(90)
leo.forward(100)
leo.right(90)
leo.forward(100)
leo.end_fill()

