import turtle

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("red")
mike.begin_fill()
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("orange")
mike.begin_fill()
mike.forward(100)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("green")
mike.begin_fill()
mike.forward(200)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("blue")
mike.begin_fill()
mike.forward(300)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("cyan")
mike.begin_fill()
mike.forward(400)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()


mike = turtle.Turtle()
mike.shape("turtle")
mike.color("red")
mike.begin_fill()
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("orange")
mike.begin_fill()
mike.backward(200)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("green")
mike.begin_fill()
mike.backward(300)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("blue")
mike.begin_fill()
mike.backward(400)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("cyan")
mike.begin_fill()
mike.backward(500)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("red")
mike.begin_fill()
mike.up(100)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("orange")
mike.begin_fill()
mike.up(100)
mike.forward(100)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("green")
mike.begin_fill()
mike.up(100)
mike.forward(200)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("blue")
mike.begin_fill()
mike.up(100)
mike.forward(300)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("cyan")
mike.begin_fill()
mike.up(100)
mike.forward(400)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.forward(100)
mike.left(90)
mike.end_fill()


mike = turtle.Turtle()
mike.shape("turtle")
mike.color("red")
mike.begin_fill()
mike.up(100)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("orange")
mike.begin_fill()
mike.up(100)
mike.backward(200)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("green")
mike.begin_fill()
mike.up(100)
mike.backward(300)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("blue")
mike.begin_fill()
mike.up(100)
mike.backward(400)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()

mike = turtle.Turtle()
mike.shape("turtle")
mike.color("cyan")
mike.begin_fill()
mike.up(100)
mike.backward(500)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.backward(100)
mike.right(90)
mike.end_fill()


